[package]
name = "simplified_othello"
version = "0.1.0"
authors = ["Logan Saso <logansaso+tech@gmail.com>"]
edition = "2018"

[dependencies]
rand = {version = "0.6.5", optional = true}

[features]
default = []
with_random = ["rand"]

[[bin]]
name = "othello"
path = "src/main.rs"
